SKILLS = [
    {"day": 1, "category": "quantitative", "name": "Order of operations",
     "description": "When you see addition, subtraction, multiplication, and division together, do multiplication and division before addition and subtraction."},
    {"day": 2, "category": "nonverbal", "name": "Rotational symmetry",
     "description": "A shape has rotational symmetry if it looks exactly the same when you turn it part-way around its center."},
    {"day": 3, "category": "verbal", "name": "Synonyms with shades of meaning",
     "description": "Happy, joyful, and elated all mean glad, but elated is the strongest feeling of all three."},
    {"day": 4, "category": "quantitative", "name": "Greatest common factor",
     "description": "The greatest common factor is the largest number that divides evenly into two numbers. It is useful when you need to reduce fractions."},
    {"day": 5, "category": "verbal", "name": "Author's purpose",
     "description": "Writers write to inform, to persuade, or to entertain. Sometimes a piece does more than one of these at once."},
    {"day": 6, "category": "nonverbal", "name": "Reflection symmetry",
     "description": "A shape has reflection symmetry if you can draw a line through it and each side is a mirror image of the other."},
    {"day": 7, "category": "quantitative", "name": "Ratios and proportions",
     "description": "A ratio compares two quantities. If a ratio stays the same as the quantities change, that is called a proportion."},
    {"day": 8, "category": "verbal", "name": "Context clues for vocabulary",
     "description": "When you read an unfamiliar word, look at the words and sentences around it. They often contain clues to the meaning."},
    {"day": 9, "category": "nonverbal", "name": "Part-to-whole relationships",
     "description": "Some patterns show how smaller pieces relate to a complete shape. Look for what is missing from the whole to identify the rule."},
    {"day": 10, "category": "quantitative", "name": "Factors and multiples",
     "description": "Factors are numbers that divide evenly into a given number. Multiples are what you get when you multiply a number by integers."},
    {"day": 11, "category": "verbal", "name": "Main idea versus supporting details",
     "description": "The main idea is the central point of a paragraph. Supporting details are facts or examples that back it up."},
    {"day": 12, "category": "nonverbal", "name": "Compound transformations",
     "description": "Some patterns change two or three properties at once: size, color, and rotation together. Track each change separately, then combine them."},
    {"day": 13, "category": "quantitative", "name": "Arithmetic sequences",
     "description": "In an arithmetic sequence, the same number is added or subtracted each step. Find the difference and the pattern becomes clear."},
    {"day": 14, "category": "verbal", "name": "Analogy types: function to object",
     "description": "In a function-to-object analogy, one word names an action and the other names the thing that performs it: write is to pen as cut is to scissors."},
    {"day": 15, "category": "nonverbal", "name": "Figure classification by hidden property",
     "description": "Sometimes figures belong together because of a property that is not obvious at first glance, like having an even number of sides or containing a right angle."},
    {"day": 16, "category": "quantitative", "name": "Geometric sequences",
     "description": "In a geometric sequence, each term is multiplied by the same number to get the next one. Find the ratio between consecutive terms to identify the rule."},
    {"day": 17, "category": "verbal", "name": "Inference: reading between the lines",
     "description": "An inference is a conclusion you draw from clues in the text, not something stated directly. Good readers infer what the author implies but does not say."},
    {"day": 18, "category": "nonverbal", "name": "Paper folding: diagonal folds",
     "description": "When you fold diagonally and punch a hole, the unfolded paper has holes in a diagonal mirror pattern. Trace the fold lines to predict the positions."},
    {"day": 19, "category": "quantitative", "name": "Algebraic thinking: one-step equations",
     "description": "An equation with one unknown can be solved by thinking about what number makes both sides equal. This is the foundation of algebra."},
    {"day": 20, "category": "verbal", "name": "Category membership and exceptions",
     "description": "In verbal classification, three words share a category and the fourth fits that same category. Watch for tricky near-matches that belong to a different group."},
    {"day": 21, "category": "nonverbal", "name": "Matrix patterns: 3x3 grids",
     "description": "In a 3-by-3 matrix, look at each row and each column separately. The rule that applies to rows often applies to columns too."},
    {"day": 22, "category": "quantitative", "name": "Two-step number puzzles",
     "description": "Some equations require two operations to solve. Work from the outside in: undo the last operation first, then the first operation."},
    {"day": 23, "category": "verbal", "name": "Degree words: intensity scale",
     "description": "Words like warm, hot, and scorching describe the same quality at different intensities. Placing them on a scale is a useful reasoning skill."},
    {"day": 24, "category": "nonverbal", "name": "Counting edges and angles",
     "description": "Figures with the same number of edges or angles often belong together in classification problems, even when they look very different."},
    {"day": 25, "category": "quantitative", "name": "Prime numbers",
     "description": "A prime number has exactly two factors: one and itself. Recognizing primes quickly helps with factoring and fraction problems."},
    {"day": 26, "category": "verbal", "name": "Restatement: saying the same thing differently",
     "description": "A restatement says the same idea in different words. It is not a summary, which shortens ideas, but a paraphrase, which replaces the words."},
    {"day": 27, "category": "nonverbal", "name": "Identifying the rule in a pattern",
     "description": "Before answering a pattern question, name the rule in words. If you cannot explain it, you have not fully understood it yet."},
    {"day": 28, "category": "quantitative", "name": "Fraction basics: equivalent fractions",
     "description": "Two fractions are equivalent when they represent the same part of a whole. Multiply or divide both numerator and denominator by the same number."},
    {"day": 29, "category": "verbal", "name": "Cause-and-effect relationships",
     "description": "In cause-and-effect analogies, one word names the cause and the other the result. Rain causes floods the same way heat causes melting."},
    {"day": 30, "category": "nonverbal", "name": "Tracing symmetry in abstract figures",
     "description": "Abstract figures may have hidden symmetry. Try rotating them mentally or imagine folding them to find axes of symmetry."},
    {"day": 31, "category": "quantitative", "name": "Long division with remainders",
     "description": "When a number does not divide evenly, the leftover is the remainder. Write it as R followed by the remainder value, for example 17 divided by 5 is 3 R 2."},
    {"day": 32, "category": "verbal", "name": "Compare and contrast across passages",
     "description": "When two passages cover the same topic, look for what they agree on and what they emphasize differently. The differences often matter more than the similarities."},
    {"day": 33, "category": "nonverbal", "name": "Scaling transformations",
     "description": "When a figure is scaled up or down in a pattern, its shape stays the same but its size changes. Track whether the rule applies uniformly to all dimensions."},
    {"day": 34, "category": "quantitative", "name": "Reducing fractions using GCF",
     "description": "To reduce a fraction, divide both the numerator and denominator by their greatest common factor. The result is the simplest form."},
    {"day": 35, "category": "verbal", "name": "Tone and mood in a passage",
     "description": "Tone is the author's attitude toward the subject. Mood is how the reader feels. Both are conveyed through word choice, not just the events described."},
    {"day": 36, "category": "nonverbal", "name": "Multiple folds before punching",
     "description": "When paper is folded more than once before punching, each fold doubles the number of holes. Track each fold carefully to predict the full pattern."},
    {"day": 37, "category": "quantitative", "name": "Fibonacci-like sequences",
     "description": "In a Fibonacci-like sequence, each term is the sum of the two terms before it. Spotting this rule requires looking at three consecutive terms at once."},
    {"day": 38, "category": "verbal", "name": "Part-to-whole verbal analogies",
     "description": "In a part-to-whole analogy, one word names a component and the other names the larger thing it belongs to: chapter is to book as scene is to play."},
    {"day": 39, "category": "nonverbal", "name": "Inside and outside shapes",
     "description": "Some figures in classification problems share the property of having one shape inside another. The types of shapes may vary but the relationship stays the same."},
    {"day": 40, "category": "quantitative", "name": "Two-digit by two-digit multiplication",
     "description": "Break the multiplication into parts: multiply by the ones digit, then by the tens digit, then add the partial products together. Column alignment is critical."},
    {"day": 41, "category": "verbal", "name": "Paragraph topic versus main idea",
     "description": "The topic is what a paragraph is about in general, often one or two words. The main idea is the specific point the paragraph makes about that topic."},
    {"day": 42, "category": "nonverbal", "name": "Alternating patterns",
     "description": "Some sequences alternate between two rules rather than following one rule straight through. Look at odd-numbered terms separately from even-numbered terms."},
    {"day": 43, "category": "quantitative", "name": "Squaring and cubing numbers",
     "description": "Squaring a number means multiplying it by itself. Cubing means multiplying it by itself twice more. These appear in number analogy rules at advanced levels."},
    {"day": 44, "category": "verbal", "name": "Sequence and chronological reasoning",
     "description": "When events have a natural order, either by time or by logic, putting them in the correct sequence requires identifying the cause-and-effect chain."},
    {"day": 45, "category": "nonverbal", "name": "Rotation versus reflection",
     "description": "Rotation turns a shape; reflection flips it. A rotated shape and its mirror image look similar but are not the same. Check the orientation of asymmetric details."},
    {"day": 46, "category": "quantitative", "name": "Multistep word problem structure",
     "description": "Even when there are no word problems here, recognizing the hidden equation structure in a number puzzle is the same skill used in algebra later."},
    {"day": 47, "category": "verbal", "name": "Antonyms and contrast in analogies",
     "description": "In an antonym analogy, both pairs must be opposites. Make sure the relationship is the same type in both pairs, not just vaguely similar."},
    {"day": 48, "category": "nonverbal", "name": "Shading patterns across rows and columns",
     "description": "In matrix problems, shading sometimes follows a rule across each row and also down each column simultaneously. Check both directions."},
    {"day": 49, "category": "quantitative", "name": "Patterns with increasing differences",
     "description": "In some sequences the gaps between terms are not constant but are themselves increasing or decreasing. Write out the differences to find the second-level rule."},
    {"day": 50, "category": "verbal", "name": "Precise vocabulary at Grade 4-5",
     "description": "Words like deduce, infer, categorize, and analyze describe thinking operations. Knowing these words precisely helps you identify exactly what a question is asking."},
    {"day": 51, "category": "nonverbal", "name": "Asymmetric punch patterns",
     "description": "When a punch lands off-center on a folded sheet, unfolding creates an asymmetric pattern. Mark the fold lines first, then reflect the punch position across each one."},
    {"day": 52, "category": "quantitative", "name": "Divisibility rules",
     "description": "A number is divisible by 3 if its digits sum to a multiple of 3. By 9 if the digit sum is a multiple of 9. By 2 if it ends in an even digit. These shortcuts save time."},
    {"day": 53, "category": "verbal", "name": "Logical sequence in writing",
     "description": "Well-organized writing has a clear flow: an opening claim, supporting points in a logical order, and a conclusion that ties back to the claim."},
    {"day": 54, "category": "nonverbal", "name": "Negative space as a pattern element",
     "description": "In some figure problems, the background or surrounding space is part of the pattern. Look at both the filled and unfilled regions to identify the rule."},
    {"day": 55, "category": "quantitative", "name": "Fraction comparison using benchmarks",
     "description": "Compare fractions to benchmark values like one-half or one whole. A fraction greater than one-half has a numerator more than half the denominator."},
    {"day": 56, "category": "verbal", "name": "Degree of certainty in language",
     "description": "Words like might, could, and may show uncertainty. Words like must, will, and is show certainty. Authors choose these words deliberately."},
    {"day": 57, "category": "nonverbal", "name": "Consistent attribute changes",
     "description": "In a well-formed matrix, every transformation follows the same rule in every row and column. If one cell seems wrong, check whether you have identified the rule correctly."},
    {"day": 58, "category": "quantitative", "name": "Multi-digit division estimation",
     "description": "Before solving a long division problem exactly, estimate the quotient by rounding the divisor to a friendly number. This catches arithmetic errors early."},
    {"day": 59, "category": "verbal", "name": "Synthesizing across multiple paragraphs",
     "description": "When a passage has several paragraphs, each paragraph contributes one piece of the full picture. The main idea of the whole passage must account for all of them."},
    {"day": 60, "category": "nonverbal", "name": "Combining pattern rules for complex problems",
     "description": "At the most advanced level, figure problems combine rotation, scaling, shading, and counting rules simultaneously. Decompose the rule into parts and track each separately."},
]


def get_skill_for_day(day_number: int) -> dict:
    if day_number < 1:
        day_number = 1
    idx = (day_number - 1) % len(SKILLS)
    return SKILLS[idx]
